### ISSUE TITLE
Breaks on double-splat in method signature

### ISSUE THREAD

**Issue by bquorning** [samphippen/rubyfmt#36]
* Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`
* Rubyfmt git sha: cbc2e0edd23af6abc63659bd654e5580c4521571

## Input file

```ruby
def foo(a, **b)
end
```

## Rubyfmt's output

```
Traceback (most recent call last):
  8: from ../rubyfmt/src/rubyfmt.rb:2285:in `<main>'
  7: from ../rubyfmt/src/rubyfmt.rb:2282:in `main'
  6: from ../rubyfmt/src/rubyfmt.rb:2142:in `format_program'
  5: from ../rubyfmt/src/rubyfmt.rb:2142:in `each'
  4: from ../rubyfmt/src/rubyfmt.rb:2143:in `block in format_program'
  3: from ../rubyfmt/src/rubyfmt.rb:2136:in `format_expression'
  2: from ../rubyfmt/src/rubyfmt.rb:2057:in `block in format_expression'
  1: from ../rubyfmt/src/rubyfmt.rb:462:in `format_def'
../rubyfmt/src/rubyfmt.rb:558:in `format_params': dont know how to deal with a params list (RuntimeError)
```

## This breaks because

Fill out this section with what Rubyfmt should have done.

**Comment by samphippen** [comment]
Fixed by de14f858a4cd6fc408502d1a1dcae7809f50f5ff

**Comment by bquorning** [comment]
I am sorry, but the issue seems to be fixed only for method calls, not for method signatures. I.e.
 `foo(a, **b)` works not, but  `def foo(a, **b) ; end` still doesn’t.

**Comment by bquorning** [comment]
Please do re-open this issue.

**Comment by bquorning** [comment]
It looks like `#format_params` needs something like `kwrest_params = params[6] || []` and a `#format_kwrest_params` method much like the existing `#format_rest_params` method.

**Comment by bquorning** [comment]
Proposed fix in #90.
